"""Offline, deterministic backend. Runs the entire tournament with no API key,
no Docker, and no training cost — so the harness, scoring, and reports can be
built and tested in isolation.

It is not random: every quantity is hash-derived from stable identifiers, so the
same inputs always yield the same matrix. The numbers are shaped to behave like
the real dynamics we expect:

  * a builder model has a latent *skill*;
  * a higher-skill builder writes a higher-*quality*, well-calibrated env
    (and very low skill sometimes yields a broken env — the validate path);
  * an agent's *competence* comes from the quality of the env it trained in;
  * a cross-eval score rises when agent competence clears the env's difficulty.

This lets us exercise non-trivial matrices (good training grounds, discriminative
golden benchmarks, broken envs scoring zero) before wiring real HUD.
"""

from __future__ import annotations

import hashlib
import math

from ..artifacts import Agent, EvalResult, GeneratedEnv, env_id
from ..spec import Spec

_ENV_TEMPLATE = '''\
# Auto-generated by MockBackend for spec {spec_id!r} by builder {builder!r}.
# A real backend replaces this with the builder model's actual HUD code.
from hud import Environment

env = Environment(name={env_name!r})


@env.template()
async def task_0(prompt: str = {prompt!r}):
    answer = yield prompt
    # reward rule (from spec): {reward}
    yield 1.0 if answer else 0.0
'''


def _unit(*parts: str) -> float:
    """Stable float in [0, 1) from the given identifier parts."""
    h = hashlib.sha256("\x1f".join(parts).encode()).digest()
    return int.from_bytes(h[:8], "big") / 2**64


def _sigmoid(x: float) -> float:
    return 1.0 / (1.0 + math.exp(-x))


class MockBackend:
    name = "mock"

    def __init__(self, broken_threshold: float = 0.12, **_: object) -> None:
        # Builders below this skill occasionally emit an invalid environment.
        self.broken_threshold = broken_threshold

    # -- build ------------------------------------------------------------

    def build(self, spec: Spec, builder_model: str) -> GeneratedEnv:
        skill = _unit("skill", builder_model)
        # Quality of the produced env: mostly the builder's skill, nudged by
        # how richly the spec is described (objective + task count).
        spec_richness = min(1.0, 0.3 + 0.1 * len(spec.tasks) + 0.4 * bool(spec.environment.objective))
        quality = 0.7 * skill + 0.3 * spec_richness
        # Difficulty the env poses to an agent evaluated on it. Centered so that
        # a competent agent lands mid-range rather than saturating at 0 or 1.
        difficulty = 0.30 + 0.30 * _unit("difficulty", builder_model, spec.id)

        eid = env_id(builder_model, spec.id)
        broken = _unit("broken", builder_model, spec.id) < self.broken_threshold and skill < 0.45
        prompt = spec.tasks[0].prompt if spec.tasks else spec.environment.objective
        reward = spec.tasks[0].reward.spec if spec.tasks else "answer present -> 1.0"
        code = _ENV_TEMPLATE.format(
            spec_id=spec.id,
            builder=builder_model,
            env_name=f"{spec.name}-{builder_model}",
            prompt=prompt or "Solve the task.",
            reward=reward or "n/a",
        )
        return GeneratedEnv(
            env_id=eid,
            builder_model=builder_model,
            spec_id=spec.id,
            code=code,
            valid=not broken,
            errors=() if not broken else ("mock: builder emitted an env that fails to import",),
            meta={"quality": round(quality, 4), "difficulty": round(difficulty, 4)},
        )

    # -- train ------------------------------------------------------------

    def train(self, env: GeneratedEnv, spec: Spec) -> Agent:
        quality = float(env.meta.get("quality", 0.5))
        # More episodes help, with diminishing returns; capped by env quality.
        episodes = max(1, spec.train.episodes)
        learn = 1.0 - math.exp(-episodes / 150.0)
        competence = quality * (0.4 + 0.6 * learn)
        return Agent(
            agent_id=f"agent::{env.env_id}",
            builder_model=env.builder_model,
            env_id=env.env_id,
            spec_id=env.spec_id,
            train_meta={"competence": round(competence, 4), "episodes": episodes},
        )

    # -- evaluate (cross-play cell) --------------------------------------

    def evaluate(self, agent: Agent, env: GeneratedEnv, spec: Spec) -> EvalResult:
        if not env.valid:
            # You cannot score against a broken environment.
            return EvalResult(agent.agent_id, env.env_id, 0.0, {"reason": "env invalid"})
        competence = float(agent.train_meta.get("competence", 0.3))
        difficulty = float(env.meta.get("difficulty", 0.5))
        noise = (_unit("eval", agent.agent_id, env.env_id) - 0.5) * 0.4
        score = _sigmoid(4.0 * (competence - difficulty) + noise)
        return EvalResult(
            agent.agent_id,
            env.env_id,
            round(score, 4),
            {"competence": competence, "difficulty": difficulty},
        )
