"""
Assemble one runnable HUD v6 `env.py` from the step-2 and step-3 handoffs.

`assemble_env` renders the source string; `compile_env` renders it and then
**compile-checks** it (syntax/AST only — no execution, no boot, no eval, matching the
current step-4 scope). The generated file is laid out so every reference resolves
top-to-bottom:

    1. module docstring  — env name, pinned version, and the user's env description
    2. imports           — hoisted + deduped from tools, the mcp block, and graders
    3. tool defs + TOOLS — the synthesized tool functions and their registry list
    4. Environment       — `env = Environment(name=..., version=...)`
    5. mcp capability    — FastMCP server exposing TOOLS (uses `env` + `TOOLS`)
    6. tasks + Taskset   — every @env.template() and the concrete task rows

The env `description` has no v6 runtime slot (Environment takes only name/version/
capabilities), so it rides along as the module docstring for provenance — never fed to
the agent or a grader.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field

from synth.contracts import SynthesizedToolset
from synth.tasks.spec import Diagnostic, SynthesizedTaskset
from synth.tools.assemble import _split_imports, mcp_capability_parts


@dataclass
class CompiledEnv:
    """The result of step 4: the env.py source, its pinned version, and diagnostics."""

    source: str
    version: str
    env_name: str
    diagnostics: list[Diagnostic] = field(default_factory=list)
    ok: bool = True  # compiled cleanly and no error-level diagnostics


def _pin_version(toolset: SynthesizedToolset, taskset: SynthesizedTaskset, override: str | None) -> str:
    """A reproducible version: a content hash of the two handoffs (no wall-clock)."""
    if override:
        return override
    blob = toolset.model_dump_json() + taskset.model_dump_json()
    digest = hashlib.sha256(blob.encode("utf-8")).hexdigest()[:8]
    return f"0.1.0+{digest}"


def _module_docstring(
    env_name: str, version: str, description: str,
    toolset: SynthesizedToolset, taskset: SynthesizedTaskset,
) -> str:
    lines: list[str] = []
    desc = (description or "").strip()
    if desc:
        lines += [desc, ""]
    tool_names = ", ".join(t.name for t in toolset.tools) or "none"
    lines += [
        f"AUTO-GENERATED by RL Scratch — HUD v6 environment {env_name!r}.",
        f"version: {version}",
        f"tools:   {len(toolset.tools)} ({tool_names})",
        f"tasks:   {taskset.task_count} concrete across {len(taskset.scenarios)} template(s)",
        "",
        "Serve with `hud serve env.py`; evaluate with `hud eval env.py <model>`.",
    ]
    body = "\n".join(lines).replace('"""', "'''")
    return f'"""{body}\n"""'


def _import_block(imports: list[str]) -> str:
    """Plain `import x` lines first, then `from x import y` (same module coalesced), sorted."""
    plain = sorted(i for i in imports if i.startswith("import "))

    by_module: dict[str, list[str]] = {}
    for line in imports:
        if not line.startswith("from "):
            continue
        head, _, names = line.partition(" import ")
        module = head[len("from "):].strip()
        bucket = by_module.setdefault(module, [])
        for name in names.split(","):
            name = name.strip()
            if name and name not in bucket:
                bucket.append(name)
    froms = [f"from {m} import {', '.join(sorted(by_module[m]))}" for m in sorted(by_module)]

    gap = [""] if plain and froms else []
    return "\n".join(plain + gap + froms)


def assemble_env(
    toolset: SynthesizedToolset,
    taskset: SynthesizedTaskset,
    *,
    description: str = "",
    version: str | None = None,
    capability_name: str = "tools",
) -> str:
    """Render the full env.py source. Pure string assembly — no compile, no execution."""
    env_name = toolset.env_name or taskset.env_name or "env"
    version = _pin_version(toolset, taskset, version)
    has_tools = bool(toolset.tools)
    has_tasks = bool(taskset.scenarios)

    # ── collect imports (deduped, order-stable) ──
    imports: list[str] = ["from hud.environment import Environment"]

    def _add(*lines: str) -> None:
        for line in lines:
            if line and line not in imports:
                imports.append(line)

    tool_defs: list[str] = []
    mcp_body = ""
    if has_tools:
        for tool in toolset.tools:
            tool_imports, body = _split_imports(tool.source)
            _add(*tool_imports)
            tool_defs.append(body)
        mcp_imports, mcp_body = mcp_capability_parts(toolset, capability_name=capability_name)
        _add(*mcp_imports)
    if has_tasks:
        _add(*taskset.imports)  # grader imports + `from hud import Taskset`

    # ── compose sections, top to bottom ──
    sections: list[str] = [
        _module_docstring(env_name, version, description, toolset, taskset),
        _import_block(imports),
    ]

    if has_tools:
        sections.append("\n\n".join(tool_defs))
        sections.append(f"TOOLS = [{', '.join(t.name for t in toolset.tools)}]")

    sections.append(f"env = Environment(name={json.dumps(env_name)}, version={json.dumps(version)})")

    if has_tools:
        sections.append(mcp_body)

    if has_tasks:
        sections.append("\n\n".join(s.source for s in taskset.scenarios))
        calls = [c for s in taskset.scenarios for c in (s.calls or [f"{s.fn_name}()"])]
        rows = "\n".join(f"    {c}," for c in calls)
        sections.append(f"tasks = Taskset({json.dumps(env_name)}, [\n{rows}\n])")
    else:
        sections.append("tasks = []")

    return "\n\n\n".join(s for s in sections if s).rstrip() + "\n"


def compile_env(
    toolset: SynthesizedToolset,
    taskset: SynthesizedTaskset,
    *,
    description: str = "",
    version: str | None = None,
    capability_name: str = "tools",
) -> CompiledEnv:
    """Assemble env.py and compile-check it (syntax only). The step-4 entry point."""
    version_pinned = _pin_version(toolset, taskset, version)
    source = assemble_env(
        toolset, taskset, description=description, version=version, capability_name=capability_name
    )
    env_name = toolset.env_name or taskset.env_name or "env"
    diags: list[Diagnostic] = []

    # one module namespace now holds both halves — a tool fn and a task fn can't share a name.
    clashes = {t.name for t in toolset.tools} & {s.fn_name for s in taskset.scenarios}
    for name in sorted(clashes):
        diags.append(Diagnostic(
            level="error", code="env.name_collision",
            message=f"Tool and task both define {name!r}; one shadows the other in env.py.",
        ))

    ok = not clashes
    try:
        compile(source, "env.py", "exec")
    except SyntaxError as exc:
        ok = False
        diags.append(Diagnostic(level="error", code="env.syntax_error",
                                message=f"Generated env.py does not compile: {exc}"))

    return CompiledEnv(source=source, version=version_pinned, env_name=env_name, diagnostics=diags, ok=ok)
